disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - array_init
  - attributes
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

included:
  - context-eng-template
  - context-eng-templateTests
  - context-eng-templateUITests

excluded:
  - context-eng-template/Preview Content
  - build
  - .build

line_length:
  warning: 120
  error: 140
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 400
  error: 500

function_body_length:
  warning: 50
  error: 80

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
  function_level:
    warning: 5

identifier_name:
  min_length:
    warning: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - url
    - uri